# 원핫 인코딩

## KoNLPy

In [10]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 1.4MB/s 
     |████████████████████████████████| 92kB 8.3MB/s 
     |████████████████████████████████| 460kB 39.9MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [34]:
import numpy as np
from konlpy.tag import Okt

okt = Okt()
text = "단어를 숫자벡터로 변환하는 가장 기본적인 방법"

문장에서 명사만 추출

In [36]:
nouns = okt.nouns(text)
print(nouns)

['단어', '숫자', '벡터', '변환', '가장', '기본', '방법']


단어 사전을 구축하여 단어별 인덱스를 부여

In [37]:
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

{'단어': 0, '숫자': 1, '벡터': 2, '변환': 3, '가장': 4, '기본': 5, '방법': 6}


In [38]:
원-핫 인코딩

SyntaxError: ignored

In [39]:
nb_classes = len(dics)
targets = list(dics.values())
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [40]:
import tensorflow as tf 
from tensorflow.keras.preprocessing.text import Tokenizer 

## Tensorflow

In [41]:
# text = "단어를 숫자벡터로 변환하는 가장 기본적인 방법"
text = "단어 숫자 벡터 변환 가장 기본 방법"

텐서플로의 Tokenizer의 fit_on_texts 메소드에 str 문장을 넣으면, 공백을 기준으로 데이터를 분리하여 tokenizing을 하는 작업을 수행

In [42]:
tokenizer = Tokenizer() 
tokenizer.fit_on_texts([text]) 
print(tokenizer.word_index)

{'단어': 1, '숫자': 2, '벡터': 3, '변환': 4, '가장': 5, '기본': 6, '방법': 7}


단어간 인덱스 결과를 기준으로 다시 문장의 값을 인코딩 한다.  
tokenizer에는 단어별 인덱스값들이 저장된 상태이며, texts_to_sequences에 문장을 넣으면 문장의 내용을 인덱스 배열로 리턴한다.

In [43]:
encoded = tokenizer.texts_to_sequences([text])[0] 
print(encoded)

[1, 2, 3, 4, 5, 6, 7]


In [44]:
onehot = tf.keras.utils.to_categorical(encoded)
print(onehot)

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [46]:
onehot = tf.keras.utils.to_categorical(encoded, 10) 
print(onehot)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
